FROM python:3.8-slim-buster

WORKDIR /app
# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install dependencies
COPY Requirements.txt .
RUN pip install --no-cache-dir -r Requirements.txt



COPY . /app


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

