# Use the official node image from the Docker Hub
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Install Angular CLI
RUN npm install -g @angular/cli

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the project files
COPY . .

# Build the application
RUN ng build --configuration production


# Use nginx image to serve the built files
FROM nginx:1.19.2-alpine

COPY --from=0 /usr/src/app/dist/front /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]